<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<title>{{page.title}}</title>

<link rel="stylesheet" href="default.css"></link>

<link rel="alternate"
      type="application/rss+xml"
      title="Open Access Coalition &raquo; Feed"
      href="http://blog.openaccesscoalition.org/feed/"></link>

<link rel="alternate"
      type="application/rss+xml"
      title="Open Access Coalition &raquo; Comments Feed"
      href="http://blog.openaccesscoalition.org/comments/feed/"></link>

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-39406709-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

</head>

<body>

<div id="wrap">

<a href="http://openaccesscoalition.org/"><img src="logo.png" width="579" height="169"/></a>

<div class="navbar">
    <a href="http://openaccesscoalition.org/">Home</a>
    <a href="http://openaccesscoalition.org/faq.html">FAQ</a>
    <a href="http://openaccesscoalition.org/examples.html">Examples</a>
    <a href="http://openaccesscoalition.org/members.html">Members</a>
    <a href="http://blog.openaccesscoalition.org">Weblog</a>
    <a href="https://groups.google.com/forum/?fromgroups#!forum/oac-general" target="_new">Group</a>
</div>

<div id="content">

<!-- end of header -->
